groups:
  - name: ml_api_alerts
    rules:
      - alert: APIDown
        expr: up{job="fastapi-ml"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "L’API FastAPI est injoignable"
          description: "Le service FastAPI ne répond plus depuis 30 secondes."

      - alert: NoPredictions
        expr: time() - last_prediction_timestamp > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Aucune prédiction récente"
          description: "Aucune prédiction reçue depuis plus de 5 minutes."
